/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  /**
     * @minLength 3
     * @maxLength 120
     */
  name?: string;
  /** @maxLength 254 */
  email?: string;
  role?: UpdateUserDtoRole;
}
