/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCategoryDto {
  /**
     * Nome da categoria
     * @minLength 2
     * @maxLength 50
     */
  name?: string;
  /** Cor em hexadecimal */
  color?: string;
}
